os: linux
dist: bionic
language: generic
sudo: required
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - wput
      - pxz
env:
  global:
    - secure: "RmEoHQxoRB3dDrogDq7SSpJFN6wImrtfFUadNzOaYK8+ly7KJmgbzkEAPjKcx+t1FQia8g73iPsDsHQbRRkJw6Ws/iTJ1Cr62rGZJIe9QOfRRtMudoqZw8L/T2kXjFR6helKqLpktScC9J2bYk102HACBeF3fkqwvAXJarHgvRc0Ltw+snXW5qa4iAqgLbgyQm5Vmd5pG/C5ck9hjpj8qBnIEBvcaYRLBRsClv1CONd5uRRQl+NjIKj+Y3yr8pGuL5XYfkgKJjBz1Gv3mUNTtSn5rSnUx2Wa4evswxz+YEVzYrqqTS692zFHgUrL3PNYAO1arIjJACK/7cB28mFNhRZt4LkDMJGC4x7+leqJkm1CT3WnFCtarXqCFb3+Vc7Dex2p9q1oCURvBi9PKVakllqLJEUif9lkAGGxqt9mldDaC4jSYSU9LVbQjYqUl9ngAHNgX1G2L5rasiD0YGuLBg1cvhasHOep91PhRVItb46ZobNFBGWWd4WzldCKUDscgNYRKPfNaQrAzga3nXah4pcaDoUolOWIj6VYskPuf5eFWNwrNnbYN4JNwNRmCkyQpAwN2NqqHB8oVvzDFHgdgP1LEN6rlGNMNRMyR3+zoJeGLftsI2GXw9thcTWvhO6Lvia+CgsSx7N+yMkrgEKK4Z0lyQROyA41u9yODDGlGqo="
    - secure: "szaozYqPVXzlgLGamD21bLf+I4PqKEyYUL2na6RajRSGvPI67AF7vBuabcIjLIJCwdNBklqValHPA99+RyO7N1sP0wvTIb5YH9owbUaGT3BcPy92l2gYVk3SEEYh5sjvq7nlKvP1QEeiMeYBAkB1j41NSsLBP2kYYKXAvcQxYqrR5GQuQgOJlTbY9q3PSDInM5gsxHM6SNtpJf3xtlzbJq3Yvju35bFwc1XJJO5rhePFM9cODF0HUl7E0sbJYECXQFbSmNCd8/rL2dXyvt60jBH0V3GRdinVEGkM/HBuCRtfu4PvdTTsIBzYUargHpu9Nn7CzGqcRDlVTRVQV9B0x+180jtwIB14jmcxvcTYJOybMDaNqTTHO505FImGsMUPhX51oEELWgrDmnr2vLSFDPYxM18RoAZ65B82me96d4J5VB1MfpOTqK4UgrB1SDklQPGDD8oXmmCL+vek8oJKUeSjB4lDlTSNJrXz/u5adXWAP3nybMQOTzRys5AAr+V+9SEayPDgotwI37ZlhUznQ3YDM0vWeDaTwMqGC88f8S0RFTx3i/4BEZHnVjwzbC95JXErcOerPXxv4RhWDN5wAEiWQdDvpoRp/GxIDFMDTuGnwPzdTO/IIAfxUJJZBsGM+/trOiNx3w8S/lOuVRVmGW2yhvWgjXr1KZkFfjlalX0="
    - secure: "nfMM/npoUvv8JfAWZZJrlK2IJM1EPccNheBEouPacWODZ8h/GUAmA91aSUdQ3JM7kv22lXyj8P7+FHtAhUMQgIFBBoRpRNh1SHrvGO8eOp8TYOLqOkgFInJeFZiBi5lmrx4/Iv2JoO7JDZMws8o9ftcAJiNdEo10eF6pKYQKY9MDZeZgPP1q2KwAVZQbLCZdtfoOx8jSjOTz078sJzr6+9BxDsFYPs53Rt312QvZTXUoyAMY/pxGvXr0pCuBtWhsX0MMNTnhrby9/F2uEgjUXmjef3ffHuIIOfq9pGGpfsWKw6aSlei5NDAXdA7UDO9sR/HNW8IyAeFIEq22itt8AAVsJ91XipiiK2Vfj5Vp+PXSBZY/vy761Dw1b8dxdCqtV2nhTFtdTpUz/7F6NZZMuAOXcEHVJ01Vrai6sJHT9VkD8DAE7UcWrHPjVx2z0r8IGUSHIAVuLA7YxgG4xI1zIPTnine4vLEzYCTsISsPHfhWz36bC6DnD53zIbbMuClgvdjIBL+B9y6CesOQ3ojJ+KK6mKeIAqgJQGoAd2DndDqKKGFagIhePQ8ydrePPEnLGH0fDkXBOTbCJvtJCjoUN3P7lvctaVVi04w0m7FTXYmySnE4+X+HelUlsrFJ5UJ5R20EzVriZO54IAIl4/rUFOuC+9KEex/3brXFTwJS+xc="
services:
  - docker
before_install:
  - docker pull yshalsager/cyanogenmod:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-6.0-norepo-20200222.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/Edrow-6/twrp_device_Unowhy_Y10G001S4M.git device/UNOWHY/Y10G001S4M_EEA
  - rm -rf bootable/recovery && git clone https://github.com/TeamWin/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
  - rm -rf external/busybox && git clone https://github.com/omnirom/android_external_busybox -b android-9.0 --depth 1 external/busybox
  - rm -rf external/ntfs-3g && git clone https://github.com/omnirom/android_external_ntfs-3g -b android-8.1 --depth 1 external/ntfs-3g
  - rm -rf external/exfat && git clone https://github.com/omnirom/android_external_exfat -b android-8.1 --depth 1 external/exfat
  - rm -rf external/fuse && git clone https://github.com/omnirom/android_external_fuse -b android-8.0 --depth 1 external/fuse
  - ( rm -rf system/vold || true) && git clone https://github.com/omnirom/android_system_vold -b android-6.0 --depth 1 system/vold
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/cmbuild/twrp/:rw,z" yshalsager/cyanogenmod bash << EOF
    #sudo apt-get update -qqy
    #sudo apt-get install -qqy --no-install-recommends openjdk-8-jdk-headless
    cd /home/cmbuild/twrp/
    source build/envsetup.sh
    lunch omni_Y10G001S4M_EEA-userdebug
    mka recoveryimage 1>/dev/null
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - export nowTime=$(date +%Y%m%d-%H%M)
  - cp $HOME/twrp/out/target/product/Y10G001S4M_EEA/recovery.img $HOME/twrp/TWRP-$version-Y10G001S4M_EEA-$nowTime-Unofficial.img
  - cd $HOME/twrp/out/target/product/Y10G001S4M_EEA/system/
  - tar -I pxz -cf $HOME/twrp/extra-system-files-$nowTime.tar.xz *
  - cd $HOME/twrp/
  #- wput TWRP-$version-Primo_RX5-$nowTime-Unofficial.img ftp://"$FTPUser":"$FTPPass"@"$FTPHost"//TWBuild-$version-$nowTime/
  #- wput extra-system-files-$nowTime.tar.xz ftp://"$FTPUser":"$FTPPass"@"$FTPHost"//TWBuild-$version-$nowTime/
deploy:
  skip_cleanup: true
  provider: releases
  token: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    branch: master
branches:
  only:
    - master
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  email:
    - edrow6@gmail.com